### ISSUE TITLE
Error: [$compile:ctreq] http://errors.angularjs.org/1.2.12/$compile/ctreq?p0=ionList&p1=ngClick

### ISSUE THREAD

**Issue by Robbe64** [backand/IonicInAppLogin#4]
Error: [$compile:ctreq] http://errors.angularjs.org/1.2.12/$compile/ctreq?p0=ionList&p1=ngClick
    at Error (native)
    at http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:37:450
    at Q (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:77:376)
    at http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:77:434
    at Array.forEach (native)
    at q (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:38:280)
    at Q (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:77:411)
    at H (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:80:411)
    at f (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:73:399)
    at f (http://code.ionicframework.com/1.0.0-beta.3/js/ionic.bundle.min.js:73:416) <ion-item nav-clear="" menu-close="" class="dark-bg light item-icon-left item" ng-click="vm.signupFacebook()">(anonymous function) @ ionic.bundle.min.js:116(anonymous function) @ ionic.bundle.min.js:93H @ ionic.bundle.min.js:80f @ ionic.bundle.min.js:73f @ ionic.bundle.min.js:73H @ ionic.bundle.min.js:80f @ ionic.bundle.min.js:73f @ ionic.bundle.min.js:73f @ ionic.bundle.min.js:73H @ ionic.bundle.min.js:80f @ ionic.bundle.min.js:73H @ ionic.bundle.min.js:80f @ ionic.bundle.min.js:73(anonymous function) @ ionic.bundle.min.js:73d @ ionic.bundle.min.js:327(anonymous function) @ ionic.bundle.min.js:327H @ ionic.bundle.min.js:80f @ ionic.bundle.min.js:73f @ ionic.bundle.min.js:73(anonymous function) @ ionic.bundle.min.js:73(anonymous function) @ ionic.bundle.min.js:327h.$digest @ ionic.bundle.min.js:131h.$apply @ ionic.bundle.min.js:134f @ ionic.bundle.min.js:98H @ ionic.bundle.min.js:102C.onreadystatechange @ ionic.bundle.min.js:103
23livereload.js?snipver=1:191 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by Shpionus** [comment]
ion-item tag need wrap by ion-list. Please, check [pull request](https://github.com/backand/IonicInAppLogin/pull/6).
